function y = filter_design(x)
%FILTER_DESIGN 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 16-Feb-2023 14:35:55

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    % % FIR Window Raised-cosine filter designed using the FIRRCOS function.
    %
    % % All frequency values are in MHz.
    % Fs = 33.3333;  % Sampling Frequency
    %
    % N    = 32;         % Order
    % Fc   = 0.15625;    % Cutoff Frequency
    % TM   = 'Rolloff';  % Transition Mode
    % R    = 0.25;       % Rolloff
    % DT   = 'Normal';   % Design Type
    % Beta = 0.33;       % Window Parameter
    %
    % % Create the window vector for the design algorithm.
    % win = kaiser(N+1, Beta);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.00877934564898734 0.00884985073011429 ...
        0.00891620852337272 0.00897834036091605 0.00903617244724781 ...
        0.00908963597535543 0.00913866723511235 0.0091832077137514 ...
        0.00922320418822629 0.00925860880929305 0.00928937917715816 ...
        0.00931547840855523 0.00933687519512802 0.00935354385301303 ...
        0.00936546436353124 0.00937262240491461 0.00937500937500937 ...
        0.00937262240491461 0.00936546436353124 0.00935354385301303 ...
        0.00933687519512802 0.00931547840855523 0.00928937917715816 ...
        0.00925860880929305 0.00922320418822629 0.0091832077137514 ...
        0.00913866723511235 0.00908963597535543 0.00903617244724781 ...
        0.00897834036091605 0.00891620852337272 0.00884985073011429 ...
        0.00877934564898734], ...
        'CoefficientsDataType', 'Custom', ...
        'CustomCoefficientsDataType', numerictype(true,8,13));
end

s = fi(x,1,3,0,'RoundingMethod','Round','OverflowAction','Saturate');
y = step(Hd,s);


% [EOF]
